const restaurentData = [
  {
    id: "1",
    name: "Paradise Biryani",
    cuisine: "Hyderabadi, Mughlai",
    rating: 4.5,
    reviews: 15420,
    priceRange: "₹₹",
    location: "Secunderabad",
    image:
      "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&q=80&w=1000",
    deliveryTime: "30-35 min",
    menu: [
      {
        id: "p1",
        name: "Hyderabadi Chicken Biryani",
        description:
          "Aromatic basmati rice cooked with tender chicken pieces and authentic spices",
        price: 349,
        image:
          "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&q=80&w=1000",
        category: "Biryani",
        isVeg: false,
        rating: 4.6,
        reviews: 8250,
      },
      {
        id: "p2",
        name: "Mutton Biryani",
        description:
          "Tender mutton pieces cooked with fragrant rice and special spices",
        price: 449,
        image:
          "https://images.unsplash.com/photo-1642821373181-696a54913e93?auto=format&fit=crop&q=80&w=1000",
        category: "Biryani",
        isVeg: false,
        rating: 4.7,
        reviews: 6120,
      },
      {
        id: "p3",
        name: "Chicken 65",
        description:
          "Spicy deep-fried chicken with curry leaves and green chilies",
        price: 299,
        image:
          "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&q=80&w=1000",
        category: "Starters",
        isVeg: false,
        rating: 4.5,
        reviews: 4230,
      },
      {
        id: "p4",
        name: "Veg Biryani",
        description:
          "Fragrant rice cooked with mixed vegetables and aromatic spices",
        price: 299,
        image:
          "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=1000",
        category: "Biryani",
        isVeg: true,
        rating: 4.3,
        reviews: 3120,
      },
      {
        id: "p5",
        name: "Mutton Kebab",
        description: "Tender minced mutton kebabs with special spices",
        price: 399,
        image:
          "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=1000",
        category: "Starters",
        isVeg: false,
        rating: 4.6,
        reviews: 2890,
      },
    ],
  },
  {
    id: "2",
    name: "Bawarchi",
    cuisine: "North Indian, Biryani",
    rating: 4.3,
    reviews: 12350,
    priceRange: "₹₹",
    location: "RTC X Roads",
    image:
      "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&q=80&w=1000",
    deliveryTime: "35-40 min",
    menu: [
      {
        id: "b1",
        name: "Special Chicken Biryani",
        description:
          "Signature biryani with premium chicken cuts and secret spice blend",
        price: 329,
        image:
          "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&q=80&w=1000",
        category: "Biryani",
        isVeg: false,
        rating: 4.4,
        reviews: 5230,
      },
      {
        id: "b2",
        name: "Butter Chicken",
        description: "Creamy tomato-based curry with tender chicken pieces",
        price: 379,
        image:
          "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&q=80&w=1000",
        category: "Main Course",
        isVeg: false,
        rating: 4.5,
        reviews: 3890,
      },
      {
        id: "b3",
        name: "Paneer Tikka",
        description: "Grilled cottage cheese marinated in spiced yogurt",
        price: 299,
        image:
          "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&q=80&w=1000",
        category: "Starters",
        isVeg: true,
        rating: 4.3,
        reviews: 2670,
      },
      {
        id: "b4",
        name: "Dal Makhani",
        description: "Creamy black lentils slow-cooked overnight",
        price: 249,
        image:
          "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=1000",
        category: "Main Course",
        isVeg: true,
        rating: 4.4,
        reviews: 1890,
      },
      {
        id: "b5",
        name: "Chicken Kebab",
        description:
          "Tender chicken pieces marinated and grilled to perfection",
        price: 349,
        image:
          "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=1000",
        category: "Starters",
        isVeg: false,
        rating: 4.6,
        reviews: 2340,
      },
    ],
  },
  {
    id: "3",
    name: "Chutneys",
    cuisine: "South Indian",
    rating: 4.4,
    reviews: 9840,
    priceRange: "₹",
    location: "Jubilee Hills",
    image:
      "https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&q=80&w=1000",
    deliveryTime: "25-30 min",
    menu: [
      {
        id: "c1",
        name: "Masala Dosa",
        description: "Crispy dosa with spiced potato filling and chutneys",
        price: 149,
        image:
          "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=1000",
        category: "Breakfast",
        isVeg: true,
        rating: 4.5,
        reviews: 3240,
      },
      {
        id: "c2",
        name: "Idli Sambar",
        description: "Steamed rice cakes served with sambar and chutney",
        price: 99,
        image:
          "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=1000",
        category: "Breakfast",
        isVeg: true,
        rating: 4.3,
        reviews: 2180,
      },
      {
        id: "c3",
        name: "Mysore Bonda",
        description: "Deep-fried spiced potato balls",
        price: 79,
        image:
          "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=1000",
        category: "Snacks",
        isVeg: true,
        rating: 4.4,
        reviews: 1560,
      },
      {
        id: "c4",
        name: "Uttapam",
        description: "Thick rice pancake with onions and tomatoes",
        price: 129,
        image:
          "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=1000",
        category: "Breakfast",
        isVeg: true,
        rating: 4.2,
        reviews: 1890,
      },
      {
        id: "c5",
        name: "Vada",
        description: "Crispy lentil doughnuts served with sambar",
        price: 89,
        image:
          "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=1000",
        category: "Snacks",
        isVeg: true,
        rating: 4.4,
        reviews: 2120,
      },
    ],
  },
  {
    id: "4",
    name: "Shah Ghouse",
    cuisine: "Mughlai, Arabian",
    rating: 4.2,
    reviews: 11230,
    priceRange: "₹₹",
    location: "Tolichowki",
    image:
      "https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&q=80&w=1000",
    deliveryTime: "40-45 min",
    menu: [
      {
        id: "s1",
        name: "Haleem",
        description: "Rich and creamy wheat preparation with meat and lentils",
        price: 299,
        image:
          "https://images.unsplash.com/photo-1639024471283-03518883512d?auto=format&fit=crop&q=80&w=1000",
        category: "Specials",
        isVeg: false,
        rating: 4.6,
        reviews: 4520,
      },
      {
        id: "s2",
        name: "Mutton Paya",
        description: "Traditional goat trotters soup",
        price: 349,
        image:
          "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?auto=format&fit=crop&q=80&w=1000",
        category: "Specials",
        isVeg: false,
        rating: 4.5,
        reviews: 3210,
      },
      {
        id: "s3",
        name: "Zafrani Biryani",
        description: "Saffron-flavored biryani with tender meat",
        price: 399,
        image:
          "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&q=80&w=1000",
        category: "Biryani",
        isVeg: false,
        rating: 4.4,
        reviews: 2890,
      },
      {
        id: "s4",
        name: "Shawarma",
        description: "Grilled meat wrapped in rumali roti with garlic sauce",
        price: 199,
        image:
          "https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&q=80&w=1000",
        category: "Arabian",
        isVeg: false,
        rating: 4.3,
        reviews: 3450,
      },
      {
        id: "s5",
        name: "Mandi",
        description: "Arabic rice dish with slow-cooked meat",
        price: 499,
        image:
          "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?auto=format&fit=crop&q=80&w=1000",
        category: "Arabian",
        isVeg: false,
        rating: 4.5,
        reviews: 2780,
      },
    ],
  },
  {
    id: "5",
    name: "Minerva Coffee Shop",
    cuisine: "South Indian, Chinese",
    rating: 4.3,
    reviews: 8750,
    priceRange: "₹",
    location: "Himayatnagar",
    image:
      "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&q=80&w=1000",
    deliveryTime: "30-35 min",
    menu: [
      {
        id: "m1",
        name: "Filter Coffee",
        description: "Traditional South Indian filter coffee",
        price: 49,
        image:
          "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&q=80&w=1000",
        category: "Beverages",
        isVeg: true,
        rating: 4.7,
        reviews: 2890,
      },
      {
        id: "m2",
        name: "Schezwan Noodles",
        description: "Spicy Chinese-style noodles with vegetables",
        price: 199,
        image:
          "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80&w=1000",
        category: "Chinese",
        isVeg: true,
        rating: 4.3,
        reviews: 1890,
      },
      {
        id: "m3",
        name: "Manchurian",
        description: "Indo-Chinese style vegetable balls in spicy sauce",
        price: 179,
        image:
          "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80&w=1000",
        category: "Chinese",
        isVeg: true,
        rating: 4.4,
        reviews: 2120,
      },
      {
        id: "m4",
        name: "Masala Tea",
        description: "Indian spiced tea with milk",
        price: 39,
        image:
          "https://images.unsplash.com/photo-1561336313-0bd5e0b27ec8?auto=format&fit=crop&q=80&w=1000",
        category: "Beverages",
        isVeg: true,
        rating: 4.5,
        reviews: 1670,
      },
      {
        id: "m5",
        name: "Fried Rice",
        description: "Chinese-style rice with vegetables and sauces",
        price: 189,
        image:
          "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&q=80&w=1000",
        category: "Chinese",
        isVeg: true,
        rating: 4.2,
        reviews: 1890,
      },
    ],
  },
  {
    id: "6",
    name: "Karachi Bakery",
    cuisine: "Bakery, Desserts",
    rating: 4.6,
    reviews: 13420,
    priceRange: "₹₹",
    location: "Banjara Hills",
    image:
      "https://images.unsplash.com/photo-1517433670267-08bbd4be890f?auto=format&fit=crop&q=80&w=1000",
    deliveryTime: "25-30 min",
    menu: [
      {
        id: "k1",
        name: "Fruit Biscuits",
        description: "Famous fruit-flavored cookies",
        price: 199,
        image:
          "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&q=80&w=1000",
        category: "Bakery",
        isVeg: true,
        rating: 4.8,
        reviews: 6230,
      },
      {
        id: "k2",
        name: "Chocolate Pastry",
        description: "Rich chocolate layered pastry",
        price: 89,
        image:
          "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=1000",
        category: "Desserts",
        isVeg: true,
        rating: 4.6,
        reviews: 4120,
      },
      {
        id: "k3",
        name: "Osmania Biscuits",
        description: "Traditional Hyderabadi tea-time biscuits",
        price: 149,
        image:
          "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&q=80&w=1000",
        category: "Bakery",
        isVeg: true,
        rating: 4.7,
        reviews: 3890,
      },
      {
        id: "k4",
        name: "Plum Cake",
        description: "Rich fruit cake with dry fruits",
        price: 299,
        image:
          "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=1000",
        category: "Desserts",
        isVeg: true,
        rating: 4.5,
        reviews: 2670,
      },
      {
        id: "k5",
        name: "Butter Cookies",
        description: "Classic buttery shortbread cookies",
        price: 179,
        image:
          "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&q=80&w=1000",
        category: "Bakery",
        isVeg: true,
        rating: 4.4,
        reviews: 3120,
      },
    ],
  },
  {
    id: "7",
    name: "Ohri's Jiva Imperia",
    cuisine: "North Indian, Continental",
    rating: 4.4,
    reviews: 7840,
    priceRange: "₹₹₹",
    location: "Banjara Hills",
    image:
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=1000",
    deliveryTime: "45-50 min",
    menu: [
      {
        id: "o1",
        name: "Butter Chicken",
        description: "Creamy tomato-based curry with tender chicken",
        price: 449,
        image:
          "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&q=80&w=1000",
        category: "Main Course",
        isVeg: false,
        rating: 4.5,
        reviews: 3420,
      },
      {
        id: "o2",
        name: "Grilled Fish",
        description: "Fresh fish grilled with herbs and lemon",
        price: 549,
        image:
          "https://images.unsplash.com/photo-1580476262798-bddd9f4b7369?auto=format&fit=crop&q=80&w=1000",
        category: "Continental",
        isVeg: false,
        rating: 4.6,
        reviews: 2890,
      },
      {
        id: "o3",
        name: "Paneer Butter Masala",
        description: "Cottage cheese in rich tomato gravy",
        price: 399,
        image:
          "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&q=80&w=1000",
        category: "Main Course",
        isVeg: true,
        rating: 4.4,
        reviews: 2670,
      },
      {
        id: "o4",
        name: "Pasta Alfredo",
        description: "Creamy pasta with mushrooms and herbs",
        price: 379,
        image:
          "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?auto=format&fit=crop&q=80&w=1000",
        category: "Continental",
        isVeg: true,
        rating: 4.3,
        reviews: 1890,
      },
      {
        id: "o5",
        name: "Chicken Tikka",
        description: "Grilled marinated chicken with Indian spices",
        price: 429,
        image:
          "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=1000",
        category: "Starters",
        isVeg: false,
        rating: 4.7,
        reviews: 3120,
      },
    ],
  },
  {
    id: "8",
    name: "Cream Stone",
    cuisine: "Ice Cream, Desserts",
    rating: 4.5,
    reviews: 9630,
    priceRange: "₹₹",
    location: "Jubilee Hills",
    image:
      "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?auto=format&fit=crop&q=80&w=1000",
    deliveryTime: "20-25 min",
    menu: [
      {
        id: "cs1",
        name: "Death by Chocolate",
        description: "Rich chocolate ice cream with brownies and sauce",
        price: 249,
        image:
          "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&q=80&w=1000",
        category: "Desserts",
        isVeg: true,
        rating: 4.7,
        reviews: 4820,
      },
      {
        id: "cs2",
        name: "Berry Blast",
        description: "Mixed berry ice cream with fresh fruits",
        price: 229,
        image:
          "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&q=80&w=1000",
        category: "Desserts",
        isVeg: true,
        rating: 4.5,
        reviews: 3120,
      },
      {
        id: "cs3",
        name: "Nutty Delight",
        description: "Vanilla ice cream with assorted nuts and caramel",
        price: 239,
        image:
          "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&q=80&w=1000",
        category: "Desserts",
        isVeg: true,
        rating: 4.6,
        reviews: 2890,
      },
      {
        id: "cs4",
        name: "Mango Paradise",
        description: "Fresh mango ice cream with mango pulp",
        price: 219,
        image:
          "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&q=80&w=1000",
        category: "Desserts",
        isVeg: true,
        rating: 4.4,
        reviews: 2670,
      },
      {
        id: "cs5",
        name: "Chocolate Avalanche",
        description: "Five layers of different chocolate ice creams",
        price: 279,
        image:
          "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&q=80&w=1000",
        category: "Desserts",
        isVeg: true,
        rating: 4.8,
        reviews: 3890,
      },
    ],
  },
  {
    id: "9",
    name: "Pista House",
    cuisine: "Mughlai, North Indian",
    rating: 4.3,
    reviews: 10240,
    priceRange: "₹₹",
    location: "Nampally",
    image:
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&q=80&w=1000",
    deliveryTime: "35-40 min",
    menu: [
      {
        id: "ph1",
        name: "Special Haleem",
        description: "Award-winning haleem with premium meat",
        price: 349,
        image:
          "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?auto=format&fit=crop&q=80&w=1000",
        category: "Specials",
        isVeg: false,
        rating: 4.6,
        reviews: 5630,
      },
      {
        id: "ph2",
        name: "Mutton Biryani",
        description: "Traditional Hyderabadi mutton biryani",
        price: 399,
        image:
          "https://images.unsplash.com/photo-1642821373181-696a54913e93?auto=format&fit=crop&q=80&w=1000",
        category: "Biryani",
        isVeg: false,
        rating: 4.5,
        reviews: 4120,
      },
      {
        id: "ph3",
        name: "Chicken Malai Kebab",
        description: "Creamy chicken kebabs with mild spices",
        price: 329,
        image:
          "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=1000",
        category: "Starters",
        isVeg: false,
        rating: 4.4,
        reviews: 2890,
      },
      {
        id: "ph4",
        name: "Mutton Shorba",
        description: "Traditional mutton soup with Indian spices",
        price: 249,
        image:
          "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?auto=format&fit=crop&q=80&w=1000",
        category: "Soups",
        isVeg: false,
        rating: 4.3,
        reviews: 1890,
      },
      {
        id: "ph5",
        name: "Chicken Tikka Biryani",
        description: "Biryani made with marinated chicken tikka",
        price: 379,
        image:
          "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&q=80&w=1000",
        category: "Biryani",
        isVeg: false,
        rating: 4.5,
        reviews: 3120,
      },
    ],
  },
  {
    id: "10",
    name: "Concu",
    cuisine: "Desserts, Beverages",
    rating: 4.7,
    reviews: 6840,
    priceRange: "₹₹₹",
    location: "Jubilee Hills",
    image:
      "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&q=80&w=1000",
    deliveryTime: "30-35 min",
    menu: [
      {
        id: "con1",
        name: "Red Velvet Cake",
        description: "Classic red velvet cake with cream cheese frosting",
        price: 399,
        image:
          "https://images.unsplash.com/photo-1586788680434-30d324b2d46f?auto=format&fit=crop&q=80&w=1000",
        category: "Desserts",
        isVeg: true,
        rating: 4.8,
        reviews: 3240,
      },
      {
        id: "con2",
        name: "Tiramisu",
        description: "Italian coffee-flavored dessert",
        price: 449,
        image:
          "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&q=80&w=1000",
        category: "Desserts",
        isVeg: true,
        rating: 4.7,
        reviews: 2890,
      },
      {
        id: "con3",
        name: "Belgian Chocolate Shake",
        description: "Rich chocolate milkshake with whipped cream",
        price: 299,
        image:
          "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&q=80&w=1000",
        category: "Beverages",
        isVeg: true,
        rating: 4.6,
        reviews: 2120,
      },
      {
        id: "con4",
        name: "Blueberry Cheesecake",
        description: "New York style cheesecake with blueberry compote",
        price: 429,
        image:
          "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&q=80&w=1000",
        category: "Desserts",
        isVeg: true,
        rating: 4.9,
        reviews: 3450,
      },
      {
        id: "con5",
        name: "Hazelnut Brownie",
        description: "Warm chocolate brownie with hazelnut and ice cream",
        price: 349,
        image:
          "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&q=80&w=1000",
        category: "Desserts",
        isVeg: true,
        rating: 4.7,
        reviews: 2780,
      },
    ],
  },
];
